# Generated by Django 5.1.11 on 2025-09-03 09:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dojo', '0999_test_deduplication_complete_processedfinding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISTProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('supported_languages', models.JSONField(blank=True, default=list)),
                ('script_path', models.CharField(max_length=1024)),
                ('project_path', models.CharField(max_length=1024)),
                ('project_version', models.CharField(blank=True, max_length=255, null=True)),
                ('output_dir', models.CharField(default='/tmp/aist-output', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='AISTPipeline',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SAST_LAUNCHED', 'Launched'), ('UPLOADING_RESULTS', 'Uploading Results'), ('WAITING_DEDUPLICATION_FINISHED', 'Waiting Deduplication Finished'), ('WAITING_RESULT_FROM_AI', 'Waiting Result From AI'), ('FINISHED', 'Finished')], default='SAST_LAUNCHED', max_length=64)),
                ('launch_data', models.JSONField(blank=True, default=dict)),
                ('logs', models.TextField(blank=True, default='')),
                ('tests', models.ManyToManyField(blank=True, related_name='aist_pipelines', to='dojo.test')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aist_pipelines', to='aist.aistproject')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
