# Generated by Django 5.1.11 on 2025-09-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aistpipeline',
            name='run_task_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='aistpipeline',
            name='watch_task_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
