# Generated by Django 5.1.11 on 2025-09-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aist', '0002_alter_aistpipeline_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aistproject',
            name='compilable',
            field=models.BooleanField(default=False),
        ),
    ]
