# Generated by Django 5.1.11 on 2025-09-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aist', '0002_aistpipeline_run_task_id_aistpipeline_watch_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aistpipeline',
            name='watch_task_id',
        ),
        migrations.AddField(
            model_name='aistpipeline',
            name='watch_dedup_task_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
