# Generated by Django 5.1.11 on 2025-09-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aist', '0003_aistproject_compilable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aistpipeline',
            name='status',
            field=models.CharField(choices=[('SAST_LAUNCHED', 'Launched'), ('UPLOADING_RESULTS', 'Uploading Results'), ('WAITING_DEDUPLICATION_TO_FINISH', 'Waiting Deduplication To Finish'), ('WAITING_CONFIRMATION_TO_PUSH_TO_AI', 'Waiting Confirmation To Push to AI'), ('PUSH_TO_AI', 'Push to AI'), ('WAITING_RESULT_FROM_AI', 'Waiting Result From AI'), ('FINISHED', 'Finished')], default='FINISHED', max_length=64),
        ),
    ]
