# Generated by Django 5.1.11 on 2025-09-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aist', '0003_remove_aistpipeline_watch_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aistpipeline',
            name='started',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
