# Generated by Django 5.1.11 on 2025-09-07 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aist', '0004_alter_aistpipeline_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aistproject',
            name='project_version',
        ),
        migrations.AlterField(
            model_name='aistpipeline',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aist_pipelines', to='aist.aistproject'),
        ),
        migrations.CreateModel(
            name='AISTProjectVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='aist.aistproject')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='aistpipeline',
            name='project_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pipelines', to='aist.aistprojectversion'),
        ),
        migrations.AddConstraint(
            model_name='aistprojectversion',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='uniq_project_version_per_project'),
        ),
    ]
