version: '3.9'
services:
  nginx:
    environment:
      GENERATE_TLS_CERTIFICATE: 'true'
      USE_TLS: 'true'

  uwsgi:
    environment:
      AIST_PIPELINE_CODE_PATH: /app/sast-pipeline
      DD_SESSION_COOKIE_SECURE: 'True'
      DD_CSRF_COOKIE_SECURE: 'True'
    volumes:
      - type: bind
        source: ./docker/extra_settings
        target: /app/docker/extra_settings
      - defectdojo_media:${DD_MEDIA_ROOT:-/app/media}
      - ./sast-combinator/tools/sast-pipeline:/app/sast-pipeline

  celerybeat:
    environment:
      AIST_PIPELINE_CODE_PATH: /app/sast-pipeline
    volumes:
      - type: bind
        source: ./docker/extra_settings
        target: /app/docker/extra_settings
      - ./sast-combinator/tools/sast-pipeline:/app/sast-pipeline

  celeryworker:
    environment:
      AIST_PIPELINE_CODE_PATH: /app/sast-pipeline
      C_FORCE_ROOT: '1'
      DOCKER_HOST: unix:///var/run/docker.sock
      DOCKER_BUILDKIT: 1
      DD_CELERY_WORKER_POOL_TYPE: prefork
      DD_CELERY_WORKER_CONCURRENCY: 6
      DD_CELERY_WORKER_AUTOSCALE_MAX: 8
      DD_CELERY_WORKER_AUTOSCALE_MIN: 2
      DD_CELERY_WORKER_PREFETCH_MULTIPLIER: 1
      DD_CELERY_LOG_LEVEL: INFO
    user: 0:0
    volumes:
      - type: bind
        source: ./docker/extra_settings
        target: /app/docker/extra_settings
      - defectdojo_media:${DD_MEDIA_ROOT:-/app/media}
      - ./sast-combinator/tools/sast-pipeline:/app/sast-pipeline
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/aist/:/tmp/aist/

  initializer:
    environment:
      AIST_PIPELINE_CODE_PATH: /app/sast-pipeline
    volumes:
      - type: bind
        source: ./docker/extra_settings
        target: /app/docker/extra_settings
      - ./sast-combinator/tools/sast-pipeline:/app/sast-pipeline

  postgres:
    ports:
      - 127.0.0.1:5432:5432

volumes:
  defectdojo_postgres:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/work/aist/db
